/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as LearnUnitIdRouteImport } from './routes/learn.$unitId'
import { Route as LifeDialectIndexRouteImport } from './routes/life-dialect.index'
import { Route as LifeDialectIdRouteImport } from './routes/life-dialect.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnUnitIdRoute = LearnUnitIdRouteImport.update({
  id: '/learn/$unitId',
  path: '/learn/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeDialectIndexRoute = LifeDialectIndexRouteImport.update({
  id: '/life-dialect/',
  path: '/life-dialect/',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeDialectIdRoute = LifeDialectIdRouteImport.update({
  id: '/life-dialect/$id',
  path: '/life-dialect/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/learn/$unitId': typeof LearnUnitIdRoute
  '/life-dialect/$id': typeof LifeDialectIdRoute
  '/life-dialect/': typeof LifeDialectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/learn/$unitId': typeof LearnUnitIdRoute
  '/life-dialect/$id': typeof LifeDialectIdRoute
  '/life-dialect': typeof LifeDialectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/learn/$unitId': typeof LearnUnitIdRoute
  '/life-dialect/$id': typeof LifeDialectIdRoute
  '/life-dialect/': typeof LifeDialectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/review'
    | '/settings'
    | '/stats'
    | '/learn/$unitId'
    | '/life-dialect/$id'
    | '/life-dialect/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/review'
    | '/settings'
    | '/stats'
    | '/learn/$unitId'
    | '/life-dialect/$id'
    | '/life-dialect'
  id:
    | '__root__'
    | '/'
    | '/review'
    | '/settings'
    | '/stats'
    | '/learn/$unitId'
    | '/life-dialect/$id'
    | '/life-dialect/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  LearnUnitIdRoute: typeof LearnUnitIdRoute
  LifeDialectIdRoute: typeof LifeDialectIdRoute
  LifeDialectIndexRoute: typeof LifeDialectIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$unitId': {
      id: '/learn/$unitId'
      path: '/learn/$unitId'
      fullPath: '/learn/$unitId'
      preLoaderRoute: typeof LearnUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-dialect/': {
      id: '/life-dialect/'
      path: '/life-dialect'
      fullPath: '/life-dialect/'
      preLoaderRoute: typeof LifeDialectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-dialect/$id': {
      id: '/life-dialect/$id'
      path: '/life-dialect/$id'
      fullPath: '/life-dialect/$id'
      preLoaderRoute: typeof LifeDialectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  LearnUnitIdRoute: LearnUnitIdRoute,
  LifeDialectIdRoute: LifeDialectIdRoute,
  LifeDialectIndexRoute: LifeDialectIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
